version: '3.6'

# storage
volumes:
    pgdata:
        driver: local
services:
    nginx:
        restart: always
        image: nginx:latest
        expose:
          - 8080
        ports:
          - "80:8080"

        volumes:
            - ./customate/static:/service/www/customate/static
            - ./customate/media:/service/www/customate/media
            - ./customate/logs:/service/www/customate/logs
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            - customate

    customate:
#        restart: always
        build:
            context: .
            dockerfile: docker/customate/Dockerfile
        volumes:
            - ./customate:/service/www/customate
        expose:
          - 8000
        ports:
            - '8000:8000'
            - '2222:22'
        env_file:
            - ./docker/environment
        stdin_open: true
        tty: true
        links:
            - db:db
        depends_on:
            - db
#            - nginx

#        command: "gunicorn -c gunicorn_app.py customate.wsgi"
    db:
        image: postgres:10
        ports:
            - 5442:5432
        environment:
            POSTGRES_USER: customate
            POSTGRES_PASSWORD: customate
            POSTGRES_DB: customate_frontend
            PGDATA: /var/lib/postgresql/data
        volumes:
#            - ./docker/data/postgres:/var/lib/postgresql/data
            - pgdata:/var/lib/postgresql/data
