# Generated by Django 2.1.7 on 2019-02-14 15:29

import core.fields
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='address',
            name='address_line_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='country_of_birth',
            field=enumfields.fields.EnumField(blank=True, enum=core.fields.Country, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=enumfields.fields.EnumField(blank=True, enum=core.fields.Gender, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mother_maiden_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='mother maiden name'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_country_origin',
            field=enumfields.fields.EnumField(blank=True, enum=core.fields.Country, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_date_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='day of birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='passport number'),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=enumfields.fields.EnumField(blank=True, enum=core.fields.UserTitle, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
