# Generated by Django 2.1.7 on 2019-02-19 13:29

import core.fields
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190214_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=enumfields.fields.EnumField(blank=True, enum=core.fields.Country, max_length=2, null=True),
        ),
    ]
