# Generated by Django 2.1.3 on 2019-02-21 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190219_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mfa_enabled',
        ),
    ]
