# Generated by Django 2.2 on 2019-06-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190312_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Designates whether this company has only owner. Unselect this to add ability to add shareholders.', verbose_name='phone number verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number_verified',
            field=models.BooleanField(default=False, help_text='Designates whether this company has only owner. Unselect this to add ability to add shareholders.', verbose_name='phone number verified'),
        ),
    ]
