# Generated by Django 2.2 on 2019-09-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_contact_info_once_verified_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_by_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_by_phone',
            field=models.BooleanField(default=False),
        ),
    ]
