# Generated by Django 2.2 on 2019-10-09 06:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_allowed_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='remember_me',
            field=models.BooleanField(default=False, help_text='Indicates whether the system will remember user and '
                                                               'not sign out automatically', verbose_name='remember me')
        )
    ]
