# Generated by Django 2.2 on 2019-07-09 13:50

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import frontend_api.fields
import frontend_api.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_auto_20190312_1343'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_status', models.CharField(blank=True, default='Fail', max_length=100)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=frontend_api.models.default_account_data_dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_frontend_api.account_set+', to='contenttypes.ContentType')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_type', enumfields.fields.EnumField(blank=True, enum=frontend_api.fields.CompanyType, max_length=30, null=True)),
                ('registration_business_name', models.CharField(blank=True, max_length=50)),
                ('registration_number', models.CharField(blank=True, max_length=8)),
                ('vat_number', models.CharField(blank=True, max_length=12)),
                ('is_private', models.BooleanField(default=True, help_text='Designates whether this company has only owner. Unselect this to add ability adding shareholders.', verbose_name='private')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this shareholder should be treated as active. Unselect this instead of deleting it.', verbose_name='active')),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminUserAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='frontend_api.Account')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('frontend_api.account',),
        ),
        migrations.CreateModel(
            name='SubUserAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='frontend_api.Account')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('frontend_api.account',),
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('birth_date', models.DateField(verbose_name='day of birth')),
                ('country_of_residence', models.CharField(max_length=30, verbose_name='country of residence')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this shareholder should be treated as active. Unselect this instead of deleting id.', verbose_name='active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholders', to='frontend_api.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='frontend_api.Account')),
                ('account_type', enumfields.fields.EnumField(default='personal', enum=frontend_api.fields.AccountType, max_length=10)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_account_id', models.UUIDField(null=True, unique=True)),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='frontend_api.Company')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('frontend_api.account',),
        ),
        migrations.CreateModel(
            name='SubUserPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('load_funds', models.BooleanField(default=False, verbose_name='load_funds')),
                ('manage_funding_sources', models.BooleanField(default=False, verbose_name='manage funding sources')),
                ('manage_payees', models.BooleanField(default=False, verbose_name='manage_payees')),
                ('manage_schedules', models.BooleanField(default=False, verbose_name='manage schedules')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='frontend_api.SubUserAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='subuseraccount',
            name='owner_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_user_accounts', to='frontend_api.UserAccount'),
        ),
        migrations.CreateModel(
            name='AdminUserPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manage_tax', models.BooleanField(default=False, verbose_name='manage tax')),
                ('manage_fee', models.BooleanField(default=False, verbose_name='manage fee')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='frontend_api.AdminUserAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
