# Generated by Django 2.1.7 on 2019-02-14 15:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'version': 1}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='verification_status',
            field=models.CharField(blank=True, default='Fail', max_length=100),
        ),
    ]
