# Generated by Django 2.2 on 2019-07-15 23:14

import core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import frontend_api.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='schedule name')),
                ('status', enumfields.fields.EnumField(enum=frontend_api.fields.ScheduleStatus, max_length=10)),
                ('purpose', enumfields.fields.EnumField(enum=frontend_api.fields.SchedulePurpose, max_length=10)),
                ('currency', enumfields.fields.EnumField(enum=core.fields.Currency, max_length=10)),
                ('payee_id', models.UUIDField(help_text='Money recipient')),
                ('funding_source_id', models.UUIDField()),
                ('period', enumfields.fields.EnumField(enum=frontend_api.fields.SchedulePeriod, max_length=10)),
                ('number_of_payments_left', models.PositiveIntegerField(default=0, help_text='Number of payments left in the current schedule. Changes dynamically in time')),
                ('start_date', models.DateField()),
                ('payment_amount', models.PositiveIntegerField()),
                ('deposit_amount', models.PositiveIntegerField(help_text='Initial payment independent of the rest of scheduled payments', null=True)),
                ('deposit_payment_date', models.DateField(null=True)),
                ('additional_information', models.CharField(blank=True, max_length=250, null=True)),
                ('total_paid_sum', models.PositiveIntegerField(default=0, help_text="Total sum of all Schedule's paid payments")),
                ('total_sum_to_pay', models.PositiveIntegerField(default=0, help_text='Total sum that should be paid by this schedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
