# Generated by Django 2.2 on 2019-07-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0002_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='fee_amount',
            field=models.PositiveIntegerField(default=0, help_text='Approximate fee amount for all payments (including deposit) in schedule'),
        ),
    ]
