# Generated by Django 2.1.7 on 2019-02-14 15:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0002_auto_20190214_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
