# Generated by Django 2.2 on 2019-07-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0004_auto_20190718_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='payee_recipient_email',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='payee_recipient_name',
            field=models.CharField(default='', max_length=254),
        ),
    ]
