# Generated by Django 2.1.7 on 2019-03-04 09:25

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations
import frontend_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0004_auto_20190219_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=frontend_api.models.default_account_data_dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
