# Generated by Django 2.1.7 on 2019-03-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0005_auto_20190304_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuseraccount',
            options={'permissions': (('admin_account_access', 'Admin account access'), ('admin_group_account_access', 'Admin group account access'), ('manage_admin_user', 'Manage admins'), ('manage_tax', 'Manage tax'), ('manage_fee', 'Manage fee'), ('can_login_as_user', 'Login as user'))},
        ),
    ]
