# Generated by Django 2.2 on 2019-04-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0006_auto_20190314_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='payment_account_id',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
