# Generated by Django 2.2 on 2019-08-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0007_scheduled_dates_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='backup_funding_source_id',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
