# Generated by Django 2.2 on 2019-08-14 10:02

from django.db import migrations
from frontend_api.models.schedule import Schedule


def drop_field(apps, schema_editor):
    if hasattr(Schedule, 'was_accepted'):
        migrations.RemoveField(
            model_name='schedule',
            name='was_accepted',
        )


class Migration(migrations.Migration):
    dependencies = [
        ('frontend_api', '0011_fake_schedule_views'),
    ]

    operations = [
        migrations.RunPython(drop_field)
    ]
