# Generated by Django 2.2 on 2019-08-14 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0011_fake_schedule_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='was_accepted',
        ),
    ]
