# Generated by Django 2.2 on 2019-08-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0013_schedules_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulepayments',
            name='parent_payment_id',
            field=models.UUIDField(help_text='In case of follow-up payments, this points to a preceding payment UUID ', null=True),
        ),
    ]
