# Generated by Django 2.2 on 2019-08-21 18:32

from django.db import migrations, models
from frontend_api.models.schedule import SchedulePayments


def migrate_existing(apps, schema_editor):
    """
    Update newly added field with defaults from corresponding schedule
    :return:
    """
    for sh in SchedulePayments.objects.all():  # type: SchedulePayments
        sh.original_amount = sh.schedule.payment_amount
        sh.save(update_fields=['original_amount'])


class Migration(migrations.Migration):
    dependencies = [
        ('frontend_api', '0015_last_schedule_payments'),
    ]

    # select 'leaf' payments only (whose are last in payment chains)
    sql_view = """
    CREATE OR REPLACE VIEW frontend_api_last_schedulepayments AS
    SELECT id, created_at, updated_at,payment_id, parent_payment_id,funding_source_id, payment_status, schedule_id, original_amount 
    FROM frontend_api_schedulepayments AS f1
    WHERE NOT EXISTS (
      SELECT *  FROM frontend_api_schedulepayments AS f2
      WHERE f1.payment_path @> f2.payment_path
        AND f1.payment_path <> f2.payment_path
    )
    or (parent_payment_id is null and not exists (
    	SELECT payment_id, parent_payment_id, payment_status, payment_path from frontend_api_schedulepayments as f2 
    	where  f2.payment_path ~ ('*.' || replace(f1.payment_id::text,'-', '_') || '.*')::lquery
    ))
    """

    operations = [
        migrations.AddField(
            model_name='schedulepayments',
            name='original_amount',
            field=models.PositiveIntegerField(default=0, help_text='Original payment amount for retry operations'),
        ),
        migrations.RunPython(migrate_existing),
        migrations.RunSQL(sql_view)  # update view
    ]
