# Generated by Django 2.2 on 2019-08-18 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('frontend_api', '0016_original_amount_schedule_payments'),
    ]

    update_sql = """
UPDATE core_user
SET phone_number_verified = FALSE, phone_number = (SELECT format('%s%s%s%s%s%s%s%s%s%s%s', '+44', a[1], a[2], a[3], a[4], a[5], a[6], a[7], a[8], a[9], a[10])
FROM (
   SELECT ARRAY (
      SELECT trunc(random() * 10)::int
      FROM generate_series(1, 10 + core_user.is_active::int)
      ) AS a
   ) as random_phone_number)
WHERE phone_number IS NOT NULL
                 """

    operations = [
        migrations.RunSQL(update_sql),
        migrations.RunSQL("CREATE UNIQUE INDEX IF NOT EXISTS core_user_phone_number_key ON core_user(phone_number)"),
    ]
