# Generated by Django 2.2 on 2019-08-18 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('frontend_api', '0017_user_unique_phones_constraints'),
    ]

    operations = [
        migrations.RunSQL("DROP INDEX IF EXISTS core_user_phone_number_key"),
        migrations.RunSQL("CREATE UNIQUE INDEX IF NOT EXISTS core_user_phone_number_key ON core_user(phone_number) "
                          "WHERE phone_number != '' AND phone_number IS NOT NULL AND is_active = TRUE"),
    ]
