# Generated by Django 2.2 on 2019-08-23 13:54

import core.fields
from django.db import migrations, connection
import enumfields.fields
from uuid import UUID
import external_apis.payment.service as payment_service


def fill_in_schedules_payee_type(apps, schema_editor):
    """
    Update newly added field with appropriate payee type
    :return:
    """

    with connection.cursor() as c:
        c.execute("SELECT DISTINCT(payee_id) FROM frontend_api_schedule WHERE payee_type IS NULL")
        for payee_rec in c.fetchall():
            payee_id = payee_rec[0]
            pd = payment_service.Payee.get(payee_id=UUID(payee_id))
            c.execute("UPDATE frontend_api_schedule SET payee_type = '%s' WHERE payee_id = '%s'" % (pd.type, payee_id))


class Migration(migrations.Migration):
    dependencies = [
        ('frontend_api', '0018_improve_user_unique_phones_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='payee_type',
            field=enumfields.fields.EnumField(enum=core.fields.PayeeType, max_length=50, null=True),
        ),
        migrations.RunPython(fill_in_schedules_payee_type),
        migrations.AlterField(
            model_name='schedule',
            name='payee_type',
            field=enumfields.fields.EnumField(enum=core.fields.PayeeType, max_length=50, null=False),
            preserve_default=False,
        ),
    ]
