# Generated by Django 2.2 on 2019-08-23 13:54

import core.fields
from django.db import migrations, connection
import enumfields.fields
from frontend_api.core.client import PaymentApiClient

def fill_in_schedules_payee_type(apps, schema_editor):
    """
    Update newly added field with appropriate payee type
    :return:
    """
    payment_client = PaymentApiClient(None)
    with connection.cursor() as c:
        c.execute("SELECT DISTINCT(payee_id) FROM frontend_api_schedule WHERE payee_type IS NULL")
        for payee_id in c.fetchall():
            pd = payment_client.get_payee_details(payee_id[0])
            c.execute("UPDATE frontend_api_schedule SET payee_type = '%s' WHERE payee_id = '%s'" % (pd.type, payee_id[0]))
    


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0018_improve_user_unique_phones_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='payee_type',
            field=enumfields.fields.EnumField(enum=core.fields.PayeeType, max_length=50, null=True),
        ),
        migrations.RunPython(fill_in_schedules_payee_type),
        migrations.AlterField(
            model_name='schedule',
            name='payee_type',
            field=enumfields.fields.EnumField(enum=core.fields.PayeeType, max_length=50, null=False),
            preserve_default=False,
        ),
    ]
