# Generated by Django 2.2 on 2019-08-27 06:57

import core.fields
import django.core.validators
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0019_schedule_payee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='additional_information',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[
                django.core.validators.RegexValidator(
                    message='Field contains forbidden characters',
                    regex='^([a-zA-Z0-9\\/\\-\\?\\:\\.\\+ ]*)$')
            ]),

        ),
        migrations.AlterField(
            model_name='schedule',
            name='payee_type',
            field=enumfields.fields.EnumField(enum=core.fields.PayeeType, max_length=10),
        ),
        migrations.RunSQL("UPDATE frontend_api_schedule SET status = 'overdue' WHERE status = 'aborted';")
    ]
