# Generated by Django 2.2 on 2019-08-27 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0021_auto_20190827_0817'),
    ]

    operations = [
        migrations.RunSQL("UPDATE frontend_api_schedule SET payee_type = 'BANK_ACCOUNT' WHERE payee_type = 'BANK_ACCOU'"),
    ]
