# Generated by Django 2.2 on 2019-08-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0022_fix_schedule_payee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='filename',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('filename', 'schedule')},
        ),
    ]
