# Generated by Django 2.2 on 2019-08-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0023_document_and_schedule_unique_pair'),
    ]

    operations = [
        # For everyone with verified email & phone
        migrations.RunSQL("""
            UPDATE core_user SET contact_info_once_verified = TRUE
            WHERE phone_number_verified = TRUE AND email_verified = TRUE
        """),
        # For everyone with existing, related payment account
        migrations.RunSQL("""
            UPDATE core_user SET contact_info_once_verified = TRUE
            WHERE id IN (
                SELECT user_id FROM frontend_api_account WHERE id IN (
                    SELECT account_ptr_id FROM frontend_api_useraccount WHERE payment_account_id IS NOT NULL
                )
            )
        """),
    ]
