# Generated by Django 2.2 on 2019-08-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0029_updated_scheduled_dates_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='funding_source_id',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
