# Generated by Django 2.2 on 2019-09-12 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0031_blacklisted_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='frontend_api.Schedule'),
        ),
    ]
