# Generated by Django 2.2 on 2019-09-18 10:11

import core.fields
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0034_adjust_schedule_execution_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='funding_source_type',
            field=enumfields.fields.EnumField(blank=True, default=None, enum=core.fields.FundingSourceType, max_length=50, null=True),
        ),
    ]
