# Generated by Django 2.2 on 2019-09-24 05:39

import core.fields
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0035_update_funding_source_type_column'),
    ]

    # @NOTE: these calculations are not absolutely correct, because deposit amount may affect its share in the
    # fee_amount column, but I think that's not critical since we calculate the approximate fee amount
    sql_set_payment_fee_amount = """
        UPDATE frontend_api_schedule 
        SET payment_fee_amount = (fee_amount / (case when deposit_amount != 0 then number_of_payments + 1 else number_of_payments end))
    """

    sql_set_deposit_fee_amount = """
        UPDATE frontend_api_schedule 
        SET deposit_fee_amount = payment_fee_amount
        WHERE deposit_amount != 0
    """

    # @NOTE: leaving original fee_amount column for now to avoid compatibility issues, we will remove it in a while
    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='fee_amount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='payment_fee_amount',
            field=models.PositiveIntegerField(default=0, help_text='Approximate fee amount for regular payment in schedule'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='deposit_fee_amount',
            field=models.PositiveIntegerField(default=0, help_text='Approximate fee amount for deposit payment in schedule'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='backup_funding_source_type',
            field=enumfields.fields.EnumField(blank=True, default=None, enum=core.fields.FundingSourceType, max_length=50, null=True),
        ),
        migrations.RunSQL(sql_set_payment_fee_amount),
        migrations.RunSQL(sql_set_deposit_fee_amount),
    ]
