# Generated by Django 2.2 on 2019-10-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0037_recreate_schedule_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulepayments',
            name='is_deposit',
            field=models.BooleanField(default=False, help_text='Indicates whether this payment is deposit'),
        ),
    ]
