# Generated by Django 2.2 on 2019-10-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0038_extend_schedulepayment_with_deposit_flag'),
    ]

    sql_set_is_deposit_flag = """
        UPDATE frontend_api_schedulepayments 
        SET is_deposit = TRUE 
        FROM frontend_api_schedule s
        WHERE s.id = frontend_api_schedulepayments.schedule_id 
            AND s.deposit_payment_date IS NOT NULL 
            AND frontend_api_schedulepayments.parent_payment_id IS NULL 
            AND s.deposit_payment_date = date(frontend_api_schedulepayments.created_at)
    """

    operations = [
        migrations.RunSQL(sql_set_is_deposit_flag),
    ]
