# Generated by Django 2.2 on 2019-09-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0039_initialize_schedulepayment_deposit_flag'),
    ]

    sql_last_schedulepayments = """
        CREATE OR REPLACE VIEW frontend_api_last_schedulepayments AS
        SELECT id, created_at, updated_at,payment_id, parent_payment_id,funding_source_id, payment_status, schedule_id, 
            original_amount, is_deposit 
        FROM frontend_api_schedulepayments AS f1
        WHERE NOT EXISTS (
          SELECT *  FROM frontend_api_schedulepayments AS f2
          WHERE f1.payment_path @> f2.payment_path
            AND f1.payment_path <> f2.payment_path
        )
        or (parent_payment_id is null and not exists (
            SELECT payment_id, parent_payment_id, payment_status, payment_path from frontend_api_schedulepayments as f2 
            where  f2.payment_path ~ ('*.' || replace(f1.payment_id::text,'-', '_') || '.*')::lquery
        ))
    """

    operations = [
        migrations.RunSQL(sql_last_schedulepayments)
    ]
