# Generated by Django 2.2 on 2019-09-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0040_recreate_last_schedulepayments_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='fee_amount',
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_overdue',
            field=models.BooleanField(default=False, help_text='Indicates whether the schedule has overdue payments'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_processing',
            field=models.BooleanField(default=False, help_text='Preventing users from starting "pay overdue" process several times at once'),
        ),
    ]
