# Generated by Django 2.2 on 2019-09-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0041_create_schedule_state_flags'),
    ]

    sql_set_processing_state = """
        UPDATE frontend_api_schedule SET is_processing = TRUE WHERE status = 'processing'          
    """

    sql_change_processing_status = """
        UPDATE frontend_api_schedule SET status = 'open' WHERE status = 'processing'          
    """

    sql_set_overdue_state = """
        UPDATE frontend_api_schedule SET is_overdue = TRUE WHERE status = 'overdue'          
    """

    sql_change_overdue_status = """
        UPDATE frontend_api_schedule SET status = 'open' WHERE status = 'overdue'          
    """

    operations = [
        migrations.RunSQL(sql_set_processing_state),
        migrations.RunSQL(sql_change_processing_status),
        migrations.RunSQL(sql_set_overdue_state),
        migrations.RunSQL(sql_change_overdue_status),
    ]
