# Generated by Django 2.2 on 2019-09-25 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0042_fill_schedule_state_flags'),
    ]

    sql_rename_cancelled_status = """
        UPDATE frontend_api_schedule SET status = 'stopped' WHERE status = 'cancelled'          
    """

    operations = [
        migrations.RunSQL(sql_rename_cancelled_status),
    ]
