# Generated by Django 2.2 on 2019-09-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0043_renamed_schedule_cancelled_status'),
    ]

    # repeated joins
    joins = """
         inner join "core_user" as "t3" 
           on ("t3"."id" = "t1"."origin_user_id")
         inner join "frontend_api_account" as "t4" 
           on ("t4"."user_id" = "t1"."origin_user_id")
         left join "frontend_api_subuseraccount" as "t5"
           on ("t5".account_ptr_id = "t4".id)
         inner join "frontend_api_useraccount" as "t6"
           on ("t6"."account_ptr_id" = "t4"."id" OR "t6"."account_ptr_id" = "t5"."owner_account_id")
     """

    sql_one_time = """
             create view frontend_api_one_time_schedule as 
               select date(adjust_execution_date("t1"."start_date", "t1"."funding_source_type")) as "scheduled_date", 
                    "t1".*, "t6"."payment_account_id" from frontend_api_schedule as "t1" 
                 {joins}  
               where "t1"."period" = 'one_time'
           """.format(joins=joins)

    sql_weekly = """
       create view frontend_api_weekly_schedule as
         select date("t2") as "scheduled_date", "t1".*, "t6"."payment_account_id" from frontend_api_schedule as "t1" 
         left join generate_series(adjust_execution_date("t1"."start_date", "t1"."funding_source_type"), 
                                   adjust_execution_date("t1"."start_date", "t1"."funding_source_type")+'5 years', '1 week'::interval) as "t2" 
           on true
         {joins}  
         where "t1"."period" = 'weekly' and 
         t2 <= adjust_execution_date("t1"."start_date", "t1"."funding_source_type") 
            + (("t1"."number_of_payments"+"t1"."number_of_payments_made") * '1 week'::interval)
     """.format(joins=joins)

    sql_monthly = """
          create view frontend_api_monthly_schedule as
            select date("t2") as "scheduled_date", "t1".*, "t6"."payment_account_id" from frontend_api_schedule as "t1" 
            left join generate_series(adjust_execution_date("t1"."start_date", "t1"."funding_source_type"), 
                                      adjust_execution_date("t1"."start_date", "t1"."funding_source_type")+'5 years', '1 month'::interval) as "t2" 
             on true
             {joins}
            where "t1"."period" = 'monthly' and 
            t2 <= adjust_execution_date("t1"."start_date", "t1"."funding_source_type") 
                + (("t1"."number_of_payments"+"t1"."number_of_payments_made") * '1 month'::interval)
        """.format(joins=joins)

    sql_quarterly = """
           create view frontend_api_quarterly_schedule as
             select date("t2") as "scheduled_date", "t1".*, "t6"."payment_account_id" from frontend_api_schedule as "t1" 
             left join generate_series(adjust_execution_date("t1"."start_date", "t1"."funding_source_type"), 
                                       adjust_execution_date("t1"."start_date", "t1"."funding_source_type")+'5 years', '4 months'::interval) as "t2" 
             on true
             {joins}
             where "t1"."period" = 'quarterly' and 
             t2 <= adjust_execution_date("t1"."start_date", "t1"."funding_source_type") 
                + (("t1"."number_of_payments"+"t1"."number_of_payments_made") * '4 months'::interval)
         """.format(joins=joins)

    sql_yearly = """
            create view frontend_api_yearly_schedule as
              select date("t2") as "scheduled_date", "t1".*, "t6"."payment_account_id" from frontend_api_schedule as "t1" 
              left join generate_series(adjust_execution_date("t1"."start_date", "t1"."funding_source_type"),
                                        adjust_execution_date("t1"."start_date", "t1"."funding_source_type")+'10 years', '1 year'::interval) as "t2" 
              on true
              {joins}
              where "t1"."period" = 'yearly' and 
              t2 <= adjust_execution_date("t1"."start_date", "t1"."funding_source_type") 
                + (("t1"."number_of_payments"+"t1"."number_of_payments_made") * '1 year'::interval)
          """.format(joins=joins)

    # deposit payment schedule
    sql_deposits = """
             create view frontend_api_deposits_schedule as
               select date(adjust_execution_date("t1"."deposit_payment_date", "t1"."funding_source_type")) as "scheduled_date", 
                    "t1".*, "t6"."payment_account_id"  from frontend_api_schedule as "t1" 
               {joins}
               where "t1"."deposit_payment_date" is not NULL 
              """.format(joins=joins)

    operations = [
        migrations.RunSQL("DROP VIEW IF EXISTS public.frontend_api_one_time_schedule"),
        migrations.RunSQL(sql_one_time),
        migrations.RunSQL("DROP VIEW IF EXISTS public.frontend_api_weekly_schedule"),
        migrations.RunSQL(sql_weekly),
        migrations.RunSQL("DROP VIEW IF EXISTS public.frontend_api_monthly_schedule"),
        migrations.RunSQL(sql_monthly),
        migrations.RunSQL("DROP VIEW IF EXISTS public.frontend_api_quarterly_schedule"),
        migrations.RunSQL(sql_quarterly),
        migrations.RunSQL("DROP VIEW IF EXISTS public.frontend_api_yearly_schedule"),
        migrations.RunSQL(sql_yearly),
        migrations.RunSQL("DROP VIEW IF EXISTS public.frontend_api_deposits_schedule"),
        migrations.RunSQL(sql_deposits),
    ]
