# Generated by Django 2.2 on 2019-10-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0045_event_trigger_for_updating_schedule_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='key',
            field=models.CharField(blank=True, help_text='Unique filename for storing in S3 bucket.', max_length=128, null=True),
        ),
    ]
