# Generated by Django 2.2 on 2019-10-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0047_is_active_field_for_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_website_url',
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
