# Generated by Django 2.2 on 2019-11-22 16:10

import core.fields
from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import frontend_api.models
import frontend_api.models.escrow
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend_api', '0049_schedule_payments_idempotence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='escrow name')),
                ('status', enumfields.fields.EnumField(enum=frontend_api.models.escrow.EscrowStatus, max_length=10)),
                ('currency', enumfields.fields.EnumField(enum=core.fields.Currency, max_length=10)),
                ('wallet_id', models.UUIDField(help_text='Identifier of the virtual wallet, that relates to this Escrow')),
                ('payee_id', models.UUIDField(help_text="Identifier of the recipient user wallet's payee, for payments from Escrow")),
                ('transit_funding_source_id', models.UUIDField(help_text="Identifier of the transit 'blocked funds' virtual wallet's funding source, for payments from Escrow")),
                ('transit_payee_id', models.UUIDField(help_text="Identifier of the transit 'blocked funds' virtual wallet's payee, for payments to Escrow")),
                ('acceptance_deadline', models.DateField(help_text='Final deadline, after which the Escrow is rejected automatically')),
                ('additional_information', models.CharField(blank=True, max_length=250, null=True)),
                ('funder_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='escrow_funded_by_me', to=settings.AUTH_USER_MODEL)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='escrow_recieved_by_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EscrowOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', enumfields.fields.EnumField(enum=frontend_api.models.escrow.EscrowOperationType, max_length=10)),
                ('approved', models.BooleanField(default=None, help_text='current approval status', null=True)),
                ('is_expired', models.BooleanField(default=False, help_text='if TRUE, this operation should NOT be considered for execution on Escrow')),
                ('args', django.contrib.postgres.fields.jsonb.JSONField(default=frontend_api.models.escrow.default_args_data_dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text="arbitrary set of operation arguments/values depending on 'type', for instance {'sum': 10}")),
                ('escrow', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frontend_api.Escrow')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
