# Generated by Django 2.2 on 2019-11-27 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import frontend_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0050_escrow_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='escrow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='frontend_api.Escrow'),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
