# Generated by Django 2.2 on 2019-12-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('frontend_api', '0051_escrow_field_for_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escrow',
            name='acceptance_deadline',
        ),

        migrations.AddField(
            model_name='escrowoperation',
            name='approval_deadline',
            field=models.DateField(help_text='Final deadline, after which the Operation is automatically expires',
                                   null=True),
        ),

    ]
