# Generated by Django 2.2 on 2019-12-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0052_alter_escrow_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrow',
            name='transit_funding_source_id',
            field=models.UUIDField(blank=True, default=None, help_text="Identifier of the transit 'blocked funds' virtual wallet's funding source, for payments from Escrow", null=True),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='transit_payee_id',
            field=models.UUIDField(blank=True, default=None, help_text="Identifier of the transit 'blocked funds' virtual wallet's payee, for payments to Escrow", null=True),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='wallet_id',
            field=models.UUIDField(blank=True, default=None, help_text='Identifier of the virtual wallet, that relates to this Escrow', null=True),
        ),
    ]
