# Generated by Django 2.2 on 2019-12-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0054_increase_escrowoperation_type_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrow',
            name='payee_iban',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='escrow',
            name='payee_recipient_email',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='escrow',
            name='payee_recipient_name',
            field=models.CharField(default='', max_length=254),
        ),
    ]
