# Generated by Django 2.2 on 2019-12-05 11:41
import enumfields
from django.db import migrations

import frontend_api.models.escrow


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0057_transit_balance__field__for__escrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrow',
            name='status',
            field=enumfields.fields.EnumField(enum=frontend_api.models.escrow.EscrowStatus, max_length=20),
        ),
    ]
