# Generated by Django 2.2 on 2019-12-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0058_increase_escrowoperation_status_length'),
    ]

    # We allow to create several pending "load_funds" operations, all other operation types in "pending" state
    # should be present in one copy
    sql_unique_index = """
        CREATE UNIQUE INDEX pending_escrowoperation_unique ON frontend_api_escrowoperation (type, escrow_id)
            WHERE approved is NULL AND is_expired = FALSE AND type != 'load_funds';
    """

    operations = [
        migrations.RunSQL(sql_unique_index),
    ]
