# Generated by Django 2.2 on 2019-12-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0059_escrowoperation_unique_index'),
    ]

    # We DON'T allow to create several pending operations
    sql_unique_index = """
        DROP INDEX IF EXISTS pending_escrowoperation_unique;
        CREATE UNIQUE INDEX pending_escrowoperation_unique ON frontend_api_escrowoperation (type, escrow_id)
            WHERE approved is NULL AND is_expired = FALSE';
    """

    operations = [
    ]
