# Generated by Django 2.2 on 2020-01-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0067_is_disputed_escrow_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_info_verified',
            field=models.BooleanField(default=False, verbose_name='business verified',
                                      help_text='Indicates whether the business information has been verified'),
        ),
    ]
