# Generated by Django 2.2 on 2020-02-04 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0069_update_payment_account_with_owner_user'),
    ]

    sql_unique_index = """
        UPDATE core_user SET gender = 'other' WHERE gender = 'unknown'
    """

    operations = [
        migrations.RunSQL(sql_unique_index),
    ]
